// Generated by gencpp from file scorpio_base/CarPwm.msg
// DO NOT EDIT!


#ifndef SCORPIO_BASE_MESSAGE_CARPWM_H
#define SCORPIO_BASE_MESSAGE_CARPWM_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace scorpio_base
{
template <class ContainerAllocator>
struct CarPwm_
{
  typedef CarPwm_<ContainerAllocator> Type;

  CarPwm_()
    : pwml(0)
    , pwma(0)  {
    }
  CarPwm_(const ContainerAllocator& _alloc)
    : pwml(0)
    , pwma(0)  {
  (void)_alloc;
    }



   typedef int32_t _pwml_type;
  _pwml_type pwml;

   typedef int32_t _pwma_type;
  _pwma_type pwma;





  typedef boost::shared_ptr< ::scorpio_base::CarPwm_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scorpio_base::CarPwm_<ContainerAllocator> const> ConstPtr;

}; // struct CarPwm_

typedef ::scorpio_base::CarPwm_<std::allocator<void> > CarPwm;

typedef boost::shared_ptr< ::scorpio_base::CarPwm > CarPwmPtr;
typedef boost::shared_ptr< ::scorpio_base::CarPwm const> CarPwmConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scorpio_base::CarPwm_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scorpio_base::CarPwm_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::scorpio_base::CarPwm_<ContainerAllocator1> & lhs, const ::scorpio_base::CarPwm_<ContainerAllocator2> & rhs)
{
  return lhs.pwml == rhs.pwml &&
    lhs.pwma == rhs.pwma;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::scorpio_base::CarPwm_<ContainerAllocator1> & lhs, const ::scorpio_base::CarPwm_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace scorpio_base

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::scorpio_base::CarPwm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scorpio_base::CarPwm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scorpio_base::CarPwm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scorpio_base::CarPwm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scorpio_base::CarPwm_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scorpio_base::CarPwm_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scorpio_base::CarPwm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "55b251c0b3ce40f84dd141bc38bb4783";
  }

  static const char* value(const ::scorpio_base::CarPwm_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x55b251c0b3ce40f8ULL;
  static const uint64_t static_value2 = 0x4dd141bc38bb4783ULL;
};

template<class ContainerAllocator>
struct DataType< ::scorpio_base::CarPwm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scorpio_base/CarPwm";
  }

  static const char* value(const ::scorpio_base::CarPwm_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scorpio_base::CarPwm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 pwml\n"
"int32 pwma\n"
;
  }

  static const char* value(const ::scorpio_base::CarPwm_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scorpio_base::CarPwm_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pwml);
      stream.next(m.pwma);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CarPwm_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scorpio_base::CarPwm_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scorpio_base::CarPwm_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "pwml: ";
    Printer<int32_t>::stream(s, indent + "  ", v.pwml);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pwma: ";
    Printer<int32_t>::stream(s, indent + "  ", v.pwma);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCORPIO_BASE_MESSAGE_CARPWM_H
